Projections nested objects support
Tech-Fabric/CloudFabric.EventSourcing pull request #12
Opened 2022-11-01 17:09 UTC by maxxsem

2022-11-02 14:56 UTC, ustims requested changes

2022-11-02 14:56 UTC, ustims commented on Implementations/CloudFabric.Projections.ElasticSearch/ElasticSearchProjectionIndexer.cs
> +namespace CloudFabric.Projections.ElasticSearch;
Please add empty line after namespace

2022-11-03 13:10 UTC, ustims approved these changes

2022-11-04 14:41 UTC, dgon-jd approved these changes

2022-11-04 14:47 UTC, merged