Feature/add elastic search projections
Tech-Fabric/CloudFabric.EventSourcing pull request #4
Opened 2022-09-27 16:10 UTC by maxxsem

2022-09-28 11:46 UTC, ustims requested changes

2022-09-29 09:32 UTC, maxxsem commented on Implementations/CloudFabric.Projections.Postgresql/PostgresqlProjectionRepository.cs
> +            whereClause += (string.IsNullOrWhiteSpace(whereClause) ? $" {searchQuery}" : $" AND {searchQuery}");
@ustims I use ILIKE for postgresql which is case-insensitive instead of LIKE

2022-09-30 16:18 UTC, ustims approved these changes

2022-09-30 16:19 UTC, ustims approved these changes

2022-09-30 16:19 UTC, merged